version: '3.7'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      # enable hot reloading
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    
# networks:
#   docker-network:
#     driver: bridge